### ISSUE TITLE
User defined columns in Hirundo csv

### ISSUE THREAD

**Issue by mishana** [Hirundo-io/hirundo-client#87]
it will be cool to support the user providing additional columns in the csv. We just need to state on processing that we will ignore these columns during analysis. The main point is that we will include these columns in the suspects csv. This can be very helpful for example when I want to add additional metadata per bbox and have it in the output as well, like say for videos frame number, minute or any other data that I'd like to see in the output without doing "joining" myself. It can be also metadata that is derived from or explicitly present in the user's JSON and we automatically add it but ignore. For a customer like Keylabs this can be very helpful

**Comment by mishana** [comment]
@blewis @shmuli what you think?

**Comment by shmuelyo** [comment]
i literally added internal support for this in my last (and still open) PR in `hirundo-core` 😄

**Comment by mishana** [comment]
OK, then we just need to make sure that we don't strip anything away between the client and core
